version: '2'
services:
    yaldaymerchantservice-mongodb:
        container_name: yaldaymerchantservice-mongodb
        image: mongo:3.3.12
        ports:
            - "27017:27017"
        # volumes:
        #     - ~/volumes/jhipster/YaldayMerchantService/mongodb/:/data/db/
