version: '2'
services:
    yaldaymerchantservice-sonar:
        container_name: yaldaymerchantservice-sonar
        image: sonarqube:6.0-alpine
        ports:
            - 9000:9000
            - 9092:9092
